name: instacart
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas=2.2.1
  - numpy=1.26.4
  - matplotlib=3.8.4
  - seaborn=0.13.2
  - scikit-learn=1.5.2
  - joblib=1.3.2
  - mlxtend=0.23.1
  - xgboost=2.0.3
  - lightgbm=4.3.0
  - statsmodels=0.14.1
  - pip
